# Generated by Django 5.2.5 on 2025-08-19 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailSenderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caracters_per_line", models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name="MailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("raw_text", models.TextField()),
                ("justified_text", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "caracters_per_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mail.mailsenderconfig",
                    ),
                ),
            ],
        ),
    ]
